services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4200:80"          # Acess√≠vel em http://localhost:4200
    restart: unless-stopped

networks:
  mycharacter-network:
    external: true